# Custom finder for toml11 (header-only library)
if(TOML11_INCLUDE_DIRS)
    set(toml11_FOUND TRUE)
    set(TOML11_FOUND TRUE)
    message(STATUS "Found toml11: ${TOML11_INCLUDE_DIRS}")
else()
    set(toml11_FOUND FALSE)
    set(TOML11_FOUND FALSE)
endif()
